### ISSUE TITLE
Change student ID data type from string to integer

### ISSUE THREAD

**Issue by ArshansGithub** [frc-emotion/nautilus-backend#13]
<img width="373" alt="image" src="https://github.com/user-attachments/assets/8c69716f-76dd-46c9-8836-6b105d497eda">

**Comment by JSpoonerr** [comment]
This isn't a good fix. This is due to the fact that if it were to have leading zeros the stident's id may be lost. Therfore I will open a new issue later for changing the grade of the student to a integer instead of a string.
